export const ALL_FEATURES = [
    "drawing",
    "nerve-set",
    "nerve-geom",
    "cohomology",
    "orientation-arrows",
    "cochain-editor",
    "h1",
    "h2",
    "cocycle-basis",
    "cup-product",
    "space-selector",
    "presets",
    "snapshots",
    "cover-status",
    "align",
    "ring-picker",
];
